### PR TITLE
Add NERSC job postings

### PR DESCRIPTION
**Pull request by JBlaschke**

### CODE REVIEW

**Comment by vchuravy** [comment]
@logankilpatrick Can you add a link to the Discourse job sections, so that we have a place for community postings?

**Comment by ranjanan** [comment]
Is this information in a discourse post as well? We can perhaps link to the discourse posting in the community section.

**Comment by JBlaschke** [comment]
@ranjanan @vchuravy it is now: https://discourse.julialang.org/t/jobs-at-nersc/84840

**Comment by ranjanan** [comment]
Alright, closing this PR. Will update the community section with this link in a new PR.

**Comment by JBlaschke** [comment]
Thanks @ranjanan

**Pull request closed without merging**
