### PR TITLE
Checkout GitHub -> Check on GitHub

### PR DESCRIPTION
**Pull request by zdroid**
A minor fix, as "checkout" means something else in Git.

### CODE REVIEW

**Comment by travigd** [comment]
I'd prefer something like _Please feel free to **contribute on GitHub**_ where the bold bit is the GitHub link.

**Comment by zdroid** [comment]
@travigd Bold text looks bad under the h2 element, which is also bold. Why not just normal link instead?

**Comment by travigd** [comment]
Yeah I just meant normal underline link text. I was just trying to illustrate where the link should be using markdown but it occurs to me that there were better ways to do that. :)

**Comment by zdroid** [comment]
@travigd fixed

**Comment by travigd** [comment]
LGTM! Next time its helpful to include a screenshot.

**Pull request merged**
